name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Déclenche le workflow lors d'un push sur main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract GitHub SHA
        run: echo "IMAGE_TAG=$(echo $GITHUB_SHA | cut -c1-7)" >> $GITHUB_ENV

      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/hello-docker:${{ env.IMAGE_TAG }} ../ex03
          docker tag ${{ secrets.DOCKERHUB_USERNAME }}/hello-docker:${{ env.IMAGE_TAG }} ${{ secrets.DOCKERHUB_USERNAME }}/hello-docker:latest

      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/hello-docker:${{ env.IMAGE_TAG }}
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/hello-docker:latest
